services:
  bot:
    image: ghcr.io/glepzilla/shiki-cards-bot:latest    # ← неймспейс орги!
    restart: unless-stopped
    env_file: .env
    volumes:
      - rendered:/app/.cache/rendered
    networks: [proxy]
    labels:
      - traefik.enable=true
      - traefik.http.routers.shiki.rule=Host(`shiki.glepzilla.ru`)
      - traefik.http.routers.shiki.entrypoints=websecure
      - traefik.http.services.shiki.loadbalancer.server.port=8080

volumes:
  rendered:

networks:
  proxy:
    external: true
